import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>idsw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="https://d1fdloi71mui9q.cloudfront.net/nX3xVId2RRuBeFxfercV_w01C0ks36F8dQ3Xf" />

        <h1 className={styles.title}>
          Welcome to{' '}
          <a href="https://www.facebook.com/idiot.sandwichk" target={'_blank'}>
            IDSW HK
          </a>
        </h1>

        <strong>
          <p>@idiotsw</p>
        </strong>

        <div className={styles.grid}>
          <a href="https://idiotsandwichk.com/" className={styles.card}>
            <h2>Online Store &rarr;</h2>
          </a>

          <a
            href="https://docs.google.com/forms/d/e/1FAIpQLSfebXSfXKiw61XkbKD7QJbxjq5KDhpDxxm10HymPIX6U9KHUw/viewform"
            className={styles.card}
          >
            <h2>學生會優惠合作 &rarr;</h2>
          </a>

          <a
            href="https://docs.google.com/forms/d/e/1FAIpQLSdBm5TkOh-T7Of3bzxI5iYMP5utVBTIBkE5Bzloaz69tAd_mg/viewform"
            className={styles.card}
          >
            <h2>加入緣份扭蛋機 &rarr;</h2>
          </a>

          <a
            href="https://www.facebook.com/idiot.sandwichk"
            className={styles.card}
          >
            <h2>Facebook &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
}
